"""
lit_scanner.py

A script that sends scientific paper abstracts to GPT-4 and extracts structured summaries.
Requires OpenAI API key set via environment variable (OPENAI_API_KEY).
"""

import openai
import os

def summarize_paper(text):
    """
    Summarizes the key findings of a scientific paper abstract using GPT-4.

    Parameters:
    text (str): The abstract or content of the paper to summarize.

    Returns:
    str: The structured summary generated by GPT-4.
    """

    # Create a prompt that instructs GPT-4 to summarize the scientific abstract
    prompt = f"""You are a scientific research assistant. Summarize the key findings of the following paper:

{text}

Summary:"""

    # Call the OpenAI API using GPT-4 model
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )

    # Extract and return the summary content from the response
    return response['choices'][0]['message']['content']

# Example usage (commented out to prevent accidental execution)
# if __name__ == "__main__":
#     abstract = "Enter your abstract text here."
#     print(summarize_paper(abstract))
